# Generated by Django 2.2.4 on 2019-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='isBusiness',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
