# Generated by Django 2.2.4 on 2019-10-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20190821_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='isBusiness',
            field=models.BooleanField(default=False),
        ),
    ]
