# Generated by Django 2.2.4 on 2019-08-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
