# Generated by Django 2.2.4 on 2019-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isBusiness',
            field=models.BooleanField(default=False),
        ),
    ]
